---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: DC1_FABRIC

# Update p2p mtu 9000 -> 1500
p2p_uplinks_mtu: 1500

# Adjust default bfd values
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

overlay_routing_protocol: none

# Enable Route Target Membership Constraint Address Family on EVPN overlay BGP peerings (Min. EOS 4.25.1F)
# Requires use eBGP as overlay protocol.
evpn_overlay_bgp_rtc: false

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="

# Enable Route Target Membership Constraint
# evpn_overlay_bgp_rtc: true

spine:
  defaults:
    platform: vEOS-LAB
    mlag_peer_ipv4_pool: 172.31.253.0/31
    mlag_peer_l3_ipv4_pool: 172.31.253.2/31
    mlag_interfaces: '{{ mlag_interfaces_veos }}'
    virtual_router_mac_address: 00:1c:73:00:dc:01
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  nodes:
    DC1-SPINE1:
      id: 1
      mgmt_ip: 10.73.254.1/24
      mac_address: '0c:1d:c0:1d:62:01'
    DC1-SPINE2:
      id: 2
      mgmt_ip: 10.73.254.2/24
      mac_address: '0c:1d:c0:1d:62:02'

l2leaf:
  defaults:
    uplink_interfaces: ['Ethernet1', 'Ethernet2']
    uplink_switches: ['DC1-SPINE1', 'DC1-SPINE2']
    uplink_ipv4_pool: 172.31.255.0/24
    mlag_peer_ipv4_pool: 172.31.253.0/31
    mlag_peer_l3_ipv4_pool: 172.31.253.2/31
    mlag_interfaces: '{{ mlag_interfaces_veos }}'
    virtual_router_mac_address: 00:1c:73:00:dc:02
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
    DC1_LEAF1:
      bgp_as: 65101
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD01', 'DC1' ]
      nodes:
        DC1-LEAF1A:
          id: 1
          mgmt_ip: 10.73.254.11/24
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
          mac_address: '0c:1d:c0:1d:62:11'
        DC1-LEAF1B:
          id: 2
          mgmt_ip: 10.73.254.12/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
          mac_address: '0c:1d:c0:1d:62:12'
    DC1_LEAF2:
      bgp_as: 65102
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD02', 'DC1' ]
      nodes:
        DC1-LEAF2A:
          id: 3
          mgmt_ip: 10.73.254.13/24
          mac_address: '0c:1d:c0:1d:62:13'
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        DC1-LEAF2B:
          id: 4
          mgmt_ip: 10.73.254.14/24
          mac_address: '0c:1d:c0:1d:62:14'
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
