clab_runner_eos: arista/ceos:4.27.2F
clab_management_network: 10.73.252.0/24

clab_nodes:
  srv-pod01:
    kind: ceos
    image: "{{ clab_runner_eos }}"
    startup-config: intended/configs/srv-pod01.cfg
    mgmt_ipv4: 10.73.252.41
    env:
      TMODE: lacp
    binds:
        - /etc/sysctl.d/99-zceos.conf:/etc/sysctl.d/99-zceos.conf:ro

  srv-pod02:
    kind: ceos
    image: "{{ clab_runner_eos }}"
    startup-config: intended/configs/srv-pod02.cfg
    mgmt_ipv4: 10.73.252.42
    env:
      TMODE: lacp
    binds:
        - /etc/sysctl.d/99-zceos.conf:/etc/sysctl.d/99-zceos.conf:ro

  srv-pod03:
    kind: ceos
    image: "{{ clab_runner_eos }}"
    startup-config: intended/configs/srv-pod03.cfg
    mgmt_ipv4: 10.73.252.43
    env:
      TMODE: lacp
    binds:
        - /etc/sysctl.d/99-zceos.conf:/etc/sysctl.d/99-zceos.conf:ro

  evpn-core:
    kind: ceos
    image: "{{ clab_runner_eos }}"
    startup-config: intended/configs/evpn-core.cfg
    mgmt_ipv4: 10.73.252.44
    env:
      TMODE: lacp
    binds:
        - /etc/sysctl.d/99-zceos.conf:/etc/sysctl.d/99-zceos.conf:ro

  # ------------------------- #
  # --- Network Services ---- #
  # ------------------------- #
  # AAA Auth server
  radius:
    image: titom73/radius:0.3.0
    mgmt_ipv4: 10.73.252.252
    kind: linux
    binds:
      - radius_authorize:/etc/raddb/mods-config/files/authorize

  # --------------------------------------- #
  # Graphite Node                           #
  # Provides Topology Graphing and the      #
  # ability to connect to nodes in the      #
  # topology via a web/ssh session          #
  # --------------------------------------- #
  graphite:
    kind: linux
    image: netreplica/graphite
    env:
      GRAPHITE_DEFAULT_TYPE: clab
      GRAPHITE_DEFAULT_TOPO: fabric
      # CLAB_SSH_CONNECTION: ${SSH_CONNECTION}
    binds:
      # - .:/var/www/localhost/htdocs/clab   <----  This is the old path in docker image netreplica/graphite:webssh2
      - .:/htdocs/clab    # New path required for latest version
    ports:
      - 80:80
    exec:
      # - sh -c 'generate_offline_graph.sh'   # used to generate offline graphs
      - sh -c 'graphite_motd.sh 80'
    labels:
      graph-hide: yes

  oob-management:
      image: titom73/mysocket-io-ssh-client:0.3.0
      kind: linux
      publish:
      - tcp/22/arista.com

  mysocketio:
    kind: mysocketio
    image: ghcr.io/hellt/mysocketctl:0.5.0
    binds:
      - .mysocketio_token:/root/.mysocketio_token

clab_links:
 - endpoints: ["srv-pod01:eth1", "avd-agg01:eth3"]
 - endpoints: ["srv-pod02:eth1", "avd-agg02:eth3"]
# ESI links
 - endpoints: ["srv-pod03:eth3", "avd-leaf3a:eth5"]
 - endpoints: ["srv-pod03:eth4", "avd-leaf4a:eth5"]
# EVPN Gateway Links
 - endpoints: ["evpn-core:eth1", "avd-bl01a:eth5"]
 - endpoints: ["evpn-core:eth2", "avd-bl01b:eth5"]
