# execution-environment.yml
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:latest'

dependencies:
  galaxy: ../../collections.yml
  python: ../../../ansible-avd/ansible_collections/arista/avd/requirements.txt

additional_build_steps:
  prepend: |
    RUN pip install --upgrade pip setuptools
    RUN yum install -y \
        make \
        wget \
        curl \
        less \
        git \
        zsh \
        vim \
        sshpass
    RUN wget --quiet https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true \
        && echo 'plugins=(ansible common-aliases safe-paste git jsontools history git-extras)' >> $HOME/.zshrc \
        && echo 'export TERM=xterm' >>  $HOME/.zshrc \
        && echo "export LC_ALL=C.UTF-8" >> $HOME/.zshrc \
        && echo "export LANG=C.UTF-8" >> $HOME/.zshrc \
        && echo "export LC_ALL=C.UTF-8" >> $HOME/.zshrc \
        && echo "export LANG=C.UTF-8" >> $HOME/.zshrc \
        && echo 'export PATH=$PATH:/home/avd/.local/bin' >> $HOME/.zshrc
  # append:
  #   - RUN ls -la /etc
