router_bgp:
  as: '64500'
  router_id: 192.168.255.204
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  - maximum-paths 4 ecmp 4
  peer_groups:
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      maximum_routes: 12000
      send_community: all
    EVPN-OVERLAY-PEERS:
      type: evpn
      update_source: Loopback0
      bfd: true
      ebgp_multihop: '15'
      send_community: all
      maximum_routes: 0
  address_family_ipv4:
    peer_groups:
      IPv4-UNDERLAY-PEERS:
        activate: true
      EVPN-OVERLAY-PEERS:
        activate: false
  address_family_evpn:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
  neighbors:
    172.31.252.0:
      remote_as: '65105'
      description: avd-bl01a
      peer_group: IPv4-UNDERLAY-PEERS
    172.31.252.2:
      remote_as: '65105'
      description: avd-bl01b
      peer_group: IPv4-UNDERLAY-PEERS
    192.168.255.19:
      peer_group: EVPN-OVERLAY-PEERS
      description: avd-bl01a
      remote_as: '65105'
    192.168.255.20:
      peer_group: EVPN-OVERLAY-PEERS
      description: avd-bl01b
      remote_as: '65105'
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP

