version: '3'

vars:
  INVENTORY: 'inventories/inetsix-eapi'
  INVENTORY_FILE: 'inventory.yml'
  ANSIBLE_ARGS: '--diff'
  UNDERLAY: "eBGP"

tasks:
  avd:build:eapi:
    desc: Build AVD eos_designs + eos_cli_config_gen
    cmds:
      - ansible-playbook playbooks/avd-eapi-generic.yml --tags build --extra-vars "underlay_routing_protocol={{.UNDERLAY}}" -i {{.INVENTORY}}/{{.INVENTORY_FILE}} {{.ANSIBLE_ARGS}}

  avd:deploy:eapi:
    desc: Build AVD eos_designs + eos_cli_config_gen & deploy by using eAPI option
    cmds:
      - ansible-playbook playbooks/avd-eapi-generic.yml --tags "build, deploy" -extra-vars "underlay_routing_protocol={{.UNDERLAY}}" -i {{.INVENTORY}}/{{.INVENTORY_FILE}} {{.ANSIBLE_ARGS}}

  avd:apply:eapi:
    desc: Deploy configuration generated previously (avd:build:*) by using eAPI
    cmds:
      - ansible-playbook playbooks/avd-eapi-generic.yml --tags "deploy" -extra-vars "underlay_routing_protocol={{.UNDERLAY}}" -i {{.INVENTORY}}/{{.INVENTORY_FILE}} {{.ANSIBLE_ARGS}}

  ### Cloudvision section

  avd:build:cvp:
    desc: Build AVD eos_designs + eos_cli_config_gen + cv configuration generation
    cmds:
      - ansible-playbook playbooks/avd-cvp-deploy-generic.yml --tags build -i {{.INVENTORY}}/{{.INVENTORY_FILE}} {{.ANSIBLE_ARGS}}

  avd:deploy:cvp:
    desc: Build AVD eos_designs + eos_cli_config_gen & deploy by using CVP option (execute task on CV)
    cmds:
      - ansible-playbook playbooks/avd-cvp-deploy-generic.yml --extra-vars "execute_tasks=true" --tags "build,provision,apply" --extra-vars "underlay_routing_protocol={{.UNDERLAY}}" -i {{.INVENTORY}}/{{.INVENTORY_FILE}} {{.ANSIBLE_ARGS}}

  avd:provision:cvp:
    desc: Build AVD eos_designs + eos_cli_config_gen & deploy by using CVP option (DO NOT execute task on CV)
    cmds:
      - ansible-playbook playbooks/avd-cvp-deploy-generic.yml --extra-vars "execute_tasks=false" --tags "build,provision,apply" --extra-vars "underlay_routing_protocol={{.UNDERLAY}}" -i {{.INVENTORY}}/{{.INVENTORY_FILE}} {{.ANSIBLE_ARGS}}