---
- name: Convert data model from 2.x to 3.0
  hosts: all
  gather_facts: false
  connection: local
  # vars:
  #   root_dir: '{{playbook_dir}}'
  tasks:

    - name: convert data model from 2.x to 3.0
      import_role:
        name: arista.avd.upgrade_tools