---
- name: Audit Switch State based on AVD
  hosts: EOS
  connection: local
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: deploy configuration to device
      import_role:
         name: arista.avd.eos_validate_state
      when:
        - ansible_network_os is defined
        - ansible_network_os == "eos"
