---
- name: Build Switch configuration
  hosts: DC1_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    # - name: 'create cvp structure config folder: {{documentation_dir_name}}'
    #   tags: [build, generate]
    #   file:
    #     path: '{{playbook_dir}}/intended/structured_configs/cvp/'
    #     state: directory
    #     mode: 0755
    #   delegate_to: localhost
    - name: 'reset local folders for output'
      tags: [build, generate]
      import_role:
        name: arista.avd.build_output_folders
    # - name: 'create cvp structure config folder: {{documentation_dir_name}}'
    #   tags: [build, generate]
    #   file:
    #     path: '{{playbook_dir}}/intended/structured_configs/cvp/'
    #     state: directory
    #     mode: 0755
    #   delegate_to: localhost
