---
- name: Configure DHCP Service configuration for ZTP
  hosts: DHCP_SERVER
  gather_facts: false
  tasks:
    - name: 'Execute DHCP configuration role'
      import_role:
        name: arista.avd.dhcp_provisioner
      vars:
        output_dirs: '{{ inventory_dir }}'
