---
- name: Configure DHCP Service on {{ inventory_hostname }} for ZTP
  hosts: TOOLS
  gather_facts: true
  tasks:
    - name: 'Execute DHCP configuration role'
      import_role:
        name: arista.avd.dhcp_provisioner
      vars:
        ztp_mode: online
        output_dirs: '{{ inventory_dir }}'
