- name: Cloudvision v3 test playbook
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  vars:
    CVP_DEVICES:
      - fqdn: cv-dev-unit-01
        systemMacAddress: '50:01:00:e5:e3:6a'
        serialNumber: 64793E1D3DE2240F547E5964354214A4
        parentContainerName: 'cv-development'
        configlets:
            - 'cv-dev-unit-01'

  tasks:
    # --------------------
    # DEVICES
    # --------------------
    - name: "Configure devices on {{inventory_hostname}}"
      arista.cvp.cv_device_v3:
        devices: "{{CVP_DEVICES}}"
        state: absent
        apply_mode: strict
        search_key: fqdn
      register: CVP_DEVICES_RESULTS

    - name: 'Display debug'
      debug:
        msg: '{{CVP_DEVICES_RESULTS}}'