- name: Container Management in Cloudvision
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  vars:
    run_tasks: false
    run_mode: merge
    state: present

    CVP_CONTAINERS_V3:
      tg-cvp-dev:
        parentContainerName: Tenant
      leafs_TG:
        parentContainerName: tg-cvp-dev
      spines_TG:
        parentContainerName: tg-cvp-dev
        configlets:
          - 'AVD_DC1-AGG01'

  tasks:
    # - name: "collect CV facts on {{inventory_hostname}}"
    #   tags: v1
    #   arista.cvp.cv_facts:
    #   register: CVP_FACTS

    # - name: 'running cv_container in {{state}} on {{inventory_hostname}}'
    #   tags: v1
    #   arista.cvp.cv_container:
    #     cvp_facts: "{{CVP_FACTS.ansible_facts}}"
    #     topology: "{{CVP_CONTAINERS_V1}}"
    #     mode: '{{run_mode}}'
    #   register: result

    - name: 'running cv_container_v3 in {{state}} on {{inventory_hostname}}'
      tags: v3
      arista.cvp.cv_container_v3:
        topology: "{{CVP_CONTAINERS_V3}}"
        state: '{{state}}'
        apply_mode: strict
      register: result

    # - name: 'running cv_container_v4 in {{state}} on {{inventory_hostname}}'
    #   tags: v4
    #   arista.cvp.cv_container_v4:
    #     topology: "{{CVP_CONTAINERS}}"
    #     state: '{{state}}'
    #   register: result

    - name: Display result
      tags: always
      debug:
        msg: '{{result}}'
