- name: Cloudvision v3 test playbook
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  vars:
    execute_tasks: false
    CVP_DEVICES:
      - fqdn: leaf-1-unit-test
        hostname: leaf-1-unit-test
        serialNumber: A2BC886CB9408A0453A3CFDD9C251999
        parentContainerName: 'ansible-tests'
        configlets:
            - 'cvaas-unit-test-01'
            - 'leaf-1-unit-test'
            - leaf-2-unit-test
            - test_configlet
            - test_device_configlet
  tasks:
    # --------------------
    # DEVICES
    # --------------------
    - name: 'Display initial information'
      debug:
        msg: 'Connecting to {{ansible_host}} using token {{ansible_ssh_pass}}'
    - name: "Configure devices on {{inventory_hostname}}"
      arista.cvp.cv_device_v3:
        devices: "{{CVP_DEVICES}}"
        state: present
        search_key: serialNumber
      register: CVP_DEVICES_RESULTS

    - name: 'Display debug'
      debug:
        msg: '{{CVP_DEVICES_RESULTS}}'