---
port_profiles:
  ALL:
    mode: trunk
    vlans: "110-114,210,211"
  TENANT_A:
    mode: access
    vlans: "110"
  TENANT_B:
    mode: trunk
    vlans: "210-211"

servers:
  #################################
  # POD servers
  #################################
  POD04-DC2:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [Eth1]
        switch_ports: [Ethernet5]
        switches: [DC2-LEAF01A]
        profile: ALL
