---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: EAPI_FABRIC

# Update p2p mtu 9000 -> 1500
p2p_uplinks_mtu: 1500

# Adjust default bfd values
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

# underlay_routing_protocol: isis
# underlay_routing_protocol: ospf
# overlay_routing_protocol: ibgp

# AS Number to use when overlay_routing_protocol=ibgp
bgp_as: 65000

# ISIS Parameters when underlay_routing_protocol=ISIS
isis_area_id: "49.0001"
isis_site_id: "0001"

# OSPF Parameters when underlay_routing_protocol=OSPF
underlay_ospf_process_id: 100
underlay_ospf_area: 0.0.0.0
underlay_ospf_max_lsa: 12000

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: true

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="

# Spine Switches
spine:
  defaults:
    platform: vEOS-LAB
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.1.0/24
    bgp_defaults: '{{veos_bgp_defaults}}'
    mlag_peer_ipv4_pool: 172.31.253.0/31
    mlag_peer_l3_ipv4_pool: 172.31.253.2/31
  nodes:
    EAPI-SPINE1:
      id: 1
      mgmt_ip: 10.73.254.1/24
      mac_address: '0c:1d:c0:1d:62:01'
    EAPI-SPINE2:
      id: 2
      mgmt_ip: 10.73.254.2/24
      mac_address: '0c:1d:c0:1d:62:02'


# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    loopback_ipv4_pool: 192.168.255.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    uplink_interfaces: ['Ethernet1', 'Ethernet2']
    uplink_switches: ['EAPI-SPINE1', 'EAPI-SPINE2']
    uplink_ipv4_pool: 172.31.255.0/24
    mlag_peer_ipv4_pool: 172.31.253.0/31
    mlag_peer_l3_ipv4_pool: 172.31.253.2/31
    mlag_interfaces: [Ethernet3, Ethernet4]
    virtual_router_mac_address: 00:1c:73:00:dc:01
    bgp_defaults: '{{veos_bgp_defaults}}'
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
    EAPI_LEAF1:
      bgp_as: 65101
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD01', 'DC1' ]
      nodes:
        EAPI-LEAF1A:
          id: 1
          mgmt_ip: 10.73.254.11/24
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
          mac_address: '0c:1d:c0:1d:62:01'
        EAPI-LEAF1B:
          id: 2
          mgmt_ip: 10.73.254.12/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
          mac_address: '0c:1d:c0:1d:62:01'
    EAPI_LEAF2:
      bgp_as: 65102
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD02', 'DC1' ]
      nodes:
        EAPI-LEAF2A:
          id: 3
          mgmt_ip: 10.73.254.13/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        EAPI-LEAF2B:
          id: 4
          mgmt_ip: 10.73.254.14/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
    EAPI_LEAF_ESI:
      mlag: false
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD03', 'DC1' ]
      nodes:
        EAPI-LEAF3A:
          id: 5
          bgp_as: 65103
          mgmt_ip: 10.73.254.17/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [Ethernet7, Ethernet7]
        EAPI-LEAF4A:
          id: 6
          bgp_as: 65104
          mgmt_ip: 10.73.254.18/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [Ethernet8, Ethernet8]
    EAPI_BL01:
      bgp_as: 65105
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'BORDER', 'DC1' ]
      nodes:
        EAPI-BL01A:
          id: 7
          mgmt_ip: 10.73.254.15/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [Ethernet5, Ethernet5]
        EAPI-BL01B:
          id: 8
          mgmt_ip: 10.73.254.16/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [Ethernet6, Ethernet6]
    EAPI_CL01:
      bgp_as: 65106
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B', 'CENTRAL_ROUTING_LAB' ]
        tags: [ 'POD05_NODE01', 'POD05_NODE02', 'DC1' ]
      nodes:
        EAPI-CL01A:
          id: 9
          mgmt_ip: 10.73.254.19/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [Ethernet9, Ethernet9]
        EAPI-CL01B:
          id: 10
          mgmt_ip: 10.73.254.20/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [Ethernet10, Ethernet10]

l2leaf:
  defaults:
    loopback_ipv4_pool: 192.168.253.0/24
    loopback_ipv4_offset: 1
    vtep_loopback_ipv4_pool: 192.168.252.0/24
    uplink_interfaces: ['Ethernet1', 'Ethernet2']
    uplink_switches: ['EAPI-SPINE1', 'EAPI-SPINE2']
    uplink_ipv4_pool: 172.31.251.0/24
    mlag_peer_ipv4_pool: 172.31.253.0/31
    mlag_peer_l3_ipv4_pool: 172.31.253.2/31
    mlag_interfaces: [Ethernet3, Ethernet4]
    virtual_router_mac_address: 00:1c:73:00:dc:01
    bgp_defaults: '{{veos_bgp_defaults}}'
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
    EAPI_L2LEAF1:
      mlag: false
      nodes:
        EAPI-L2LEAF01:
          id: 1
          bgp_as: 65107
          mgmt_ip: 10.73.254.31/24
          uplink_switch_interfaces: [Ethernet11, Ethernet11]
          filter:
            tenants: [ 'Tenant_A', 'Tenant_B', 'CENTRAL_ROUTING_LAB' ]
            tags: [ 'POD05_NODE01' ]
          # mac_address: '0c:1d:c0:1d:62:01'
        EAPI-L2LEAF02:
          id: 2
          bgp_as: 65108
          mgmt_ip: 10.73.254.32/24
          uplink_switch_interfaces: [Ethernet12, Ethernet12]
          filter:
            tenants: [ 'Tenant_A', 'Tenant_B', 'CENTRAL_ROUTING_LAB' ]
            tags: [ 'POD05_NODE02' ]
          # mac_address: '0c:1d:c0:1d:62:01'

edge:
  defaults:
    uplink_switches: ['EAPI-LEAF1A', 'EAPI-LEAF1B']
    uplink_interfaces: ['Ethernet1', 'Ethernet2']
    mlag_peer_ipv4_pool: 172.31.253.0/31
    mlag_peer_l3_ipv4_pool: 172.31.253.2/31
  node_groups:
    EAPI_EDGE_LEAF1:
      uplink_switches: [ EAPI-LEAF1A, EAPI-LEAF1B ]
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD01', 'DC1' ]
      nodes:
        EAPI-AGG01:
          id: 9
          mgmt_ip: 10.73.254.21/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [ Ethernet5, Ethernet5 ]
    EAPI_EDGE_LEAF2:
      uplink_switches: [ EAPI-LEAF2A, EAPI-LEAF2B ]
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD02', 'DC1' ]
      nodes:
        EAPI-AGG02:
          id: 10
          mgmt_ip: 10.73.254.22/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [ Ethernet5, Ethernet5 ]
