---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: EAPI_FABRIC

# Update p2p mtu 9000 -> 1500
p2p_uplinks_mtu: 1500

# Adjust default bfd values
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

# underlay_routing_protocol: isis
# overlay_routing_protocol: ibgp

# AS Number to use when overlay_routing_protocol=ibgp
bgp_as: 65000

# ISIS Parameters when underlay_routing_protocol=ISIS
isis_area_id: "49.0001"
isis_site_id: "0001"

# OSPF Parameters when underlay_routing_protocol=OSPF
underlay_ospf_process_id: 100
underlay_ospf_area: 0.0.0.0
underlay_ospf_max_lsa: 12000

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: true

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="

# Spine Switches
spine:
  defaults:
    # Change from spine.platform to spine.defaults.platform
    platform: vEOS-LAB
    # Change from spine.bgp_as to spine.defaults.bgp_as
    bgp_as: 65001
    # Change from overlay_loopback_network_summary to spine.defaults.loopback_ipv4_pool
    loopback_ipv4_pool: 192.168.255.0/24
    # Change from spine_bgp_defaults to spine.defaults.bgp_defaults
    bgp_defaults: '{{veos_bgp_defaults}}'
    # Change from mlag_ips.mlag_peer to spine.defaults.mlag_peer_ipv4_pool
    mlag_peer_ipv4_pool: 10.255.252.0/24
    # Change from mlag_ips.mlag_peer_l3_ipv4_pool to spine.defaults.mlag_peer_l3_ipv4_pool
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
  nodes:
    EAPI-SPINE1:
      id: 1
      evpn_role: server
      mgmt_ip: 10.73.254.1/24
      mac_address: '0c:1d:c0:1d:62:01'
    EAPI-SPINE2:
      id: 2
      evpn_role: server
      mgmt_ip: 10.73.254.2/24
      mac_address: '0c:1d:c0:1d:62:02'


# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    # Change from overlay_loopback_network_summary to l3leaf.defaults.loopback_ipv4_pool
    loopback_ipv4_pool: 192.168.255.0/24
    # New loopback_network_offset variable based on max_spines or length of spine.nodes
    loopback_ipv4_offset: 2
    # Change from vtep_loopback_network_summary to l3leaf.defaults.vtep_loopback_ipv4_pool
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    # Change from l3leaf.defaults.uplink_to_uplink_switch_interfaces to l3leaf.defaults.uplink_interfaces
    uplink_interfaces: ['Ethernet1', 'Ethernet2']
    # Change from l3leaf.defaults.spines to l3leaf.defaults.uplink_switches
    uplink_switches: ['EAPI-SPINE1', 'EAPI-SPINE2']
    # Change from underlay_p2p_network_summary to l3leaf.defaults.uplink_ipv4_pool
    uplink_ipv4_pool: 172.31.255.0/24
    # Change from mlag_ips.mlag_peer to spine.defaults.mlag_peer_ipv4_pool
    mlag_peer_ipv4_pool: 10.255.252.0/24
    # Change from mlag_ips.mlag_peer_l3_ipv4_pool to spine.defaults.mlag_peer_l3_ipv4_pool
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    mlag_interfaces: [Ethernet3, Ethernet4]
    virtual_router_mac_address: 00:1c:73:00:dc:01
    # Change from leaf_bgp_defaults to l3leaf.defaults.bgp_defaults
    bgp_defaults: '{{veos_bgp_defaults}}'
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
    EAPI_LEAF1:
      bgp_as: 65101
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD01', 'DC1' ]
      nodes:
        EAPI-LEAF1A:
          id: 1
          mgmt_ip: 10.73.254.11/24
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
          mac_address: '0c:1d:c0:1d:62:01'
        EAPI-LEAF1B:
          id: 2
          mgmt_ip: 10.73.254.12/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
          mac_address: '0c:1d:c0:1d:62:01'
    EAPI_LEAF2:
      bgp_as: 65102
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD02', 'DC1' ]
        # tags: [ border ]
      nodes:
        EAPI-LEAF2A:
          id: 3
          mgmt_ip: 10.73.254.13/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        EAPI-LEAF2B:
          id: 4
          mgmt_ip: 10.73.254.14/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
    EAPI_LEAF_ESI:
      mlag: false
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD03', 'DC1' ]
        # tags: [ border ]
      nodes:
        EAPI-LEAF3A:
          id: 5
          bgp_as: 65103
          mgmt_ip: 10.73.254.17/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [Ethernet7, Ethernet7]
        EAPI-LEAF4A:
          id: 6
          bgp_as: 65104
          mgmt_ip: 10.73.254.18/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [Ethernet8, Ethernet8]
    EAPI_BL01:
      bgp_as: 65105
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'BORDER', 'DC1' ]
      nodes:
        EAPI-BL01A:
          id: 7
          mgmt_ip: 10.73.254.15/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [Ethernet5, Ethernet5]
        EAPI-BL01B:
          id: 8
          mgmt_ip: 10.73.254.16/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [Ethernet6, Ethernet6]

l2leaf:
  defaults:
    # Change from l2leaf.defaults.uplink_switches to l2leaf.defaults.uplink_switches
    uplink_switches: ['EAPI-LEAF1A', 'EAPI-LEAF1B']
    # Change from mlag_ips.mlag_peer to spine.defaults.mlag_peer_ipv4_pool
    mlag_peer_ipv4_pool: 10.255.252.0/24
    # Change from mlag_ips.mlag_peer_l3_ipv4_pool to spine.defaults.mlag_peer_l3_ipv4_pool
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
  node_groups:
    EAPI_L2LEAF1:
      uplink_switches: [ EAPI-LEAF1A, EAPI-LEAF1B ]
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD01', 'DC1' ]
        # tags: [ border ]
      nodes:
        EAPI-AGG01:
          id: 9
          mgmt_ip: 10.73.254.21/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [ Ethernet5, Ethernet5 ]
    EAPI_L2LEAF2:
      uplink_switches: [ EAPI-LEAF2A, EAPI-LEAF2B ]
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD02', 'DC1' ]
      nodes:
        EAPI-AGG02:
          id: 10
          mgmt_ip: 10.73.254.22/24
          mac_address: '0c:1d:c0:1d:62:01'
          uplink_switch_interfaces: [ Ethernet5, Ethernet5 ]
