---
# static_routes:
# - vrf: MGMT
#   destination_address_prefix: 0.0.0.0/0
#   gateway: 10.73.254.253

service_routing_protocols_model: multi-agent

ip_routing: true

# daemon_terminattr:
#   ingestgrpcurl:
#     ips:
#     - 10.73.254.1
#     port: 9910
#   ingestvrf: MGMT
#   smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
#   ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
#   disable_aaa: false

vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199

name_server:
  source:
    vrf: default
  nodes:
  - 10.73.254.253
  - 10.73.1.254

ntp_server:
  local_interface:
    vrf: default
    interface: Management0
  nodes:
  - 10.73.254.253
  - 10.73.1.254

management_interfaces:
  Management0:
    description: oob_management
    shutdown: false
    ip_address: "{{ansible_host}}/24"
    gateway: '{{ default_mgt_gateway }}'
    type: oob

clock:
  timezone: Europe/Paris

management_api_http:
  enable_vrfs:
    default: {}
  enable_https: true

management_ssh:
  enable: true
  vrfs:
    MGMT:
      enable: true

management_console:
  idle_timeout: 0

aaa_authorization:
  exec:
    default: local

ip_igmp_snooping:
  globally_enabled: true

# errdisable:
#   recovery:
#     causes:
#       - bpduguard
#       - link-flap
#       - portchannelguard
#       - speed-misconfigured
#       - uplink-failure-detection
#   interval: 300
