---
l3_edge:
  p2p_links_ip_pools:
    to_core: 10.88.2.0/24
  p2p_links_profiles:
    airbus_dci_m88:
        # Speed | Optional
        # speed: < speed | auto speed | forced speed >
        # IP Pool defined under p2p_links_ip_pools. A /31 will be taken from the pool per P2P link | Optional (Requires ip_pool or subnet or ip)
        ip_pool: to_core
        # Subnet used on this P2P link | Optional (Requires ip_pool or subnet or ip)
        # subnet: < IPv4_address/Mask >
        # Specific IP addresses used on this P2P link | Optional (Requires ip_pool or subnet or ip)
        ip: [ < node_a IPv4_address/Mask >, < node_b IPv4_address/Mask > ]
        # Nodes where this link should be configured | Required
        nodes: [ < node_a >, < node_b > ]
        # Interfaces where this link should be configured | Required
        interfaces: [ < node_a_interface >, < node_b_interface > ]
        # AS Numbers for BGP | Required with bgp peering
        as: [ < node_a_as >, < node_b_as > ]
        # Add this interface to underlay routing protocol | Optional
        include_in_underlay_protocol: false
        # MTU for this P2P link | Optional
        # mtu: < number | default -> same as p2p_uplinks_mtu >
        # Enable BFD (only considered for BGP) | Optional
        bfd: true

  p2p_links:
      # Unique id per subnet_summary. Used to calculate ip addresses | Required with ip_pool
    - id: 1
      # Profile defined under p2p_profiles | Optional
      profile: airbus_dci_m88