---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: DC1_FABRIC

# underlay_routing_protocol: ISIS
# overlay_routing_protocol: ibgp
# bgp_as: 65000

# ISIS Parameters when underlay_routing_protocol=ISIS
isis_area_id: "49.0001"
isis_site_id: "0001"

# OSPF Parameters when underlay_routing_protocol=OSPF
underlay_ospf_process_id: 100
underlay_ospf_area: 0.0.0.0
underlay_ospf_max_lsa: 12000

# Point to Point Network Summary range, assigned as /31 for each
# uplink interfaces
# Assign range larger then total [spines * total potential leafs * 2]
underlay_p2p_network_summary: 172.31.255.0/24

# IP address range for evpn loopback for all switches in fabric,
# assigned as /32s
# Assign range larger then total spines + total leafs switches
overlay_loopback_network_summary: 192.168.255.0/24

# VTEP VXLAN Tunnel source loopback IP for leaf switches, assigned in /32s
# Assign range larger then total leaf switches
vtep_loopback_network_summary: 192.168.254.0/24

# mlag pair IP assignment - assign blocks - Assign range larger then
# total spines + total leafs switches
mlag_ips:
  leaf_peer_l3: 10.255.251.0/24
  mlag_peer: 10.255.252.0/24

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: true

# Internal VLAN Allocation
internal_vlan_order:
  allocation: descending
  range:
    beginning: 4000
    ending: 4090

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="

# Spine Switches
spine:
  platform: vEOS-LAB
  bgp_as: 65001
  # defines the range of acceptable remote ASNs from leaf switches
  leaf_as_range: 65101-65132
  nodes:
    DC1-SPINE1:
      id: 1
      mgmt_ip: 10.73.1.11/16
      bgp_route_reflector: true
    DC1-SPINE2:
      id: 2
      mgmt_ip: 10.73.1.12/16
      bgp_route_reflector: true

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    # virtual router mac for VNIs assigned to Leaf switches
    # format: xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:dc:01
    platform: vEOS-LAB
    bgp_as: 65100
    spines: [DC1-SPINE1, DC1-SPINE2]
    uplink_to_spine_interfaces: [Ethernet1, Ethernet2]
    mlag_interfaces: [Ethernet3, Ethernet4]
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
    DC1_LEAF1:
      bgp_as: 65101
      filter:
        tenants: [ Tenant_A ]
        tags: [ opzone, web, app ]
        # tags: [ border ]
      nodes:
        DC1-LEAF1A:
          id: 1
          mgmt_ip: 10.73.1.13/16
          spine_interfaces: [Ethernet1, Ethernet1]
        DC1-LEAF1B:
          id: 2
          mgmt_ip: 10.73.1.14/16
          spine_interfaces: [Ethernet2, Ethernet2]
    DC1_LEAF2:
      bgp_as: 65102
      nodes:
        DC1-LEAF2A:
          id: 3
          mgmt_ip: 10.73.1.15/16
          spine_interfaces: [Ethernet3, Ethernet3]
        DC1-LEAF2B:
          id: 4
          mgmt_ip: 10.73.1.16/16
          spine_interfaces: [Ethernet4, Ethernet4]
    DC1_LEAF3:
      bgp_as: 65103
      nodes:
        DC1-LEAF3A:
          id: 8
          mgmt_ip: 10.73.1.21/16
          spine_interfaces: [Ethernet5, Ethernet5]
    DC1_LEAF4:
      bgp_as: 65104
      nodes:
        DC1-LEAF4A:
          id: 11
          mgmt_ip: 10.73.1.24/16
          spine_interfaces: [Ethernet8, Ethernet8]
    DC1_BL1:
      # bgp_as: 65110
      mlag: true
      nodes:
        DC1-BL1A:
          id: 9
          mgmt_ip: 10.73.1.22/16
          spine_interfaces: [Ethernet6, Ethernet6]
          bgp_as: 65111
        DC1-BL1B:
          id: 10
          mgmt_ip: 10.73.1.23/16
          spine_interfaces: [Ethernet7, Ethernet7]
          bgp_as: 65112

l2leaf:
  defaults:
    platform: vEOS-LAB
    parent_l3leafs: [ DC1-LEAF1A, DC1-LEAF1B ]
    uplink_interfaces: [ Ethernet1, Ethernet2 ]
    mlag_interfaces: [ Ethernet3, Ethernet4 ]
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
  node_groups:
    DC1_L2LEAF1:
      parent_l3leafs: [ DC1-LEAF1A, DC1-LEAF1B ]
      filter:
        tenants: [ Tenant_A ]
        tags: [ opzone, web, app ]
      nodes:
        DC1-L2LEAF1A:
          id: 5
          mgmt_ip: 10.73.1.17/16
          l3leaf_interfaces: [ Ethernet5, Ethernet5 ]
    DC1_L2LEAF2:
      parent_l3leafs: [ DC1-LEAF2A, DC1-LEAF2B ]
      # filter:
      #   tenants: [ Tenant_A ]
      #   tags: [ opzone, web, app ]
      nodes:
        DC1-L2LEAF2A:
          id: 7
          mgmt_ip: 10.73.1.18/16
          l3leaf_interfaces: [ Ethernet5, Ethernet5 ]
    # DC1_L2LEAF3:
    #   parent_l3leafs: [ DC1-BL1A, DC1-BL1B ]
    #   short_esi: 0909:0808:0707
    #   # filter:
    #   #   tenants: [ Tenant_A ]
    #   #   tags: [ opzone, web, app ]
    #   nodes:
    #     DC1-L2LEAF3A:
    #       id: 7
    #       mgmt_ip: 10.73.1.18/16
    #       l3leaf_interfaces: [ Ethernet5, Ethernet5 ]

#### Override for vEOS Lab Caveats ####

# Disable update wait-for-convergence and update wait-for-install,
# which is not supported in vEOS-LAB.
# Refer to design guide

spine_bgp_defaults:
  #  - update wait-for-convergence
  #  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

leaf_bgp_defaults:
  #  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

# Update p2p mtu 9000 -> 1500
p2p_uplinks_mtu: 1500

# Adjust default bfd values
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

# List of additional CVP configlets to bind to devices and containers
# Configlets MUST be configured on CVP before running AVD playbooks.
# cv_configlets:
#   containers:
#     DC1_L3LEAFS:
#       - ASE_GLOBAL-ALIASES2
#   devices:
#     DC1-L2LEAF1A:
#       - ASE_DEVICE-ALIASES

