- name: Container Management in Cloudvision
  hosts: CVP
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  vars:
    run_tasks: false
    run_mode: merge

  tasks:
    - name: "collect CV facts on {{inventory_hostname}}"
      arista.cvp.cv_facts:
      register: CVP_FACTS

    - name: 'running cv_container in {{run_mode}} on {{inventory_hostname}}'
      arista.cvp.cv_container:
        cvp_facts: "{{CVP_FACTS.ansible_facts}}"
        topology: "{{HEC_CONTAINER}}"
        mode: '{{run_mode}}'
      register: result

    - debug:
        msg: '{{result}}'
