apiVersion: apps/v1
kind: Deployment
metadata:
  name: avd-coder-deployment-cbu
  labels:
    name: avd-vscode
    run: avd-coder
    app: avd
    version: '0.0.1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avd
  template:
    metadata:
      labels:
        app: avd
        run: avd-coder
        app: avd
    spec:
      restartPolicy: Always
      containers:
        - name: avd-coder
          image: avdteam/vscode:latest
          env:
            - name: AVD_MODE
              value: "demo"
            - name: AVD_PASSWORD
              value: arista123
            - name: AVD_GIT_USER
              value: "Carl Buchmann"
            - name: AVD_GIT_EMAIL
              value: "carl.buchmann@arista.com"
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: avd-coder-service-cbu
spec:
  type: NodePort
  ports:
  - nodePort: 31082
    port: 8080
    targetPort: 8080
  selector:
    app: avd
    run: avd-coder
