---
apiVersion: v1
kind: Service
metadata:
  name: avd-documentation-service
spec:
  type: NodePort
  ports:
  - nodePort: 31080
    port: 80
    targetPort: 80
  selector:
    run: avd-web
    app: nginx