---
ansible_user: ansible
# should use vault for passwords
ansible_ssh_pass: ansible
ansible_become: true
ansible_become_method: enable
ansible_become_pass: ansible
ansible_httpapi_validate_certs: false