---
ansible_python_interpreter: $(which python)
ztp_network_summary: 10.73.255.0/24
ztp_pool_start: 10.73.255.200
ztp_pool_end: 10.73.255.210
ztp_lease_time: 300
fabric_group: 'DC1_FABRIC'
ztp_mac_source: interface
ztp_mode: offline