ethernet_interfaces:
  Ethernet1:
    description: to TLS-CORE-01 Ethernet2
    type: routed
  Ethernet1.101:
    description: to TLS-CORE-01 Ethernet2.101 - BLUE-C1
    mtu: 1500
    ip_address: 10.1.1.5/31
    vrf: BLUE-C1
    encapsulation:
      dot1q:
        vlan: 101
    ospf_network_point_to_point: true
    ospf_area: 0.0.0.0
  Ethernet1.102:
    description: to TLS-CORE-01 Ethernet2.102 - BLUE-C2
    mtu: 1500
    ip_address: 10.1.2.5/31
    vrf: BLUE-C2
    encapsulation:
      dot1q:
        vlan: 102
    ospf_network_point_to_point: true
    ospf_area: 0.0.0.0
  Ethernet1.103:
    description: to TLS-CORE-01 Ethernet2.103 - BLUE-C3
    mtu: 1500
    ip_address: 10.1.3.5/31
    vrf: BLUE-C3
    encapsulation:
      dot1q:
        vlan: 103
    ospf_network_point_to_point: true
    ospf_area: 0.0.0.0

loopback_interfaces:
  Loopback0:
    description: TLS SEDI
    ip_address: 1.0.3.1/32

  Loopback101:
    description: TLS SEDI - BLUE-C1
    vrf: BLUE-C1
    ip_address: 101.0.3.1/32
    ospf_area: 0.0.0.0

router_ospf:
  process_ids:
    101:
      vrf: BLUE-C1
      passive_interface_default: true
      router_id: 1.0.3.1
      log_adjacency_changes_detail: true
      bfd_enable: false
      no_passive_interfaces:
        - Ethernet1.101

router_bgp:
  as: 65003
  router_id: 1.0.3.1
  bgp_defaults:
    - no bgp default ipv4-unicast
    - distance bgp 20 200 200
    - graceful-restart restart-time 300
    - graceful-restart
  peer_groups:
    WELCOME_ROUTERS:
      type: ipv4
      description: 'BGP Connection to Welcome routers'
      remote_as: 65001
      update_source: Loopback101
      ebgp_multihop: 10
  address_family_ipv4:
    peer_groups:
      WELCOME_ROUTERS:
        activate: true
  vrfs:
    BLUE-C1:
      rd: 1.0.3.1:101
      neighbors:
        101.0.1.1:
          peer_group: WELCOME_ROUTERS