port_channel_interfaces:
  Port-Channel8:
    description: to TLS WELCOME 02 Port-channel 8
    type: routed
  Port-Channel8.101:
    description: to WELCOME 02 Port-Channel8.101 - BLUE-C1
    mtu: 1500
    ip_address: 10.255.1.0/31
    vrf: BLUE-C1
    encapsulation:
      dot1q:
        vlan: 101
  Port-Channel8.102:
    description: to WELCOME 02 Port-Channel8.101 - BLUE-C2
    mtu: 1500
    ip_address: 10.255.2.0/31
    vrf: BLUE-C2
    encapsulation:
      dot1q:
        vlan: 102
  Port-Channel8.103:
    description: to WELCOME 02 Port-Channel8.101 - BLUE-C3
    mtu: 1500
    ip_address: 10.255.3.0/31
    vrf: BLUE-C3
    encapsulation:
      dot1q:
        vlan: 103

ethernet_interfaces:
  Ethernet1:
    description: to WAN-OBS-01 Ethernet2
    type: routed
  Ethernet1.101:
    description: to WAN-OBS-01 Ethernet2.101 - BLUE-C1
    mtu: 1500
    ip_address: 10.1.1.1/31
    vrf: BLUE-C1
    encapsulation:
      dot1q:
        vlan: 101
  Ethernet1.102:
    description: to WAN-OBS-01 Ethernet2.102 - BLUE-C2
    mtu: 1500
    ip_address: 10.1.2.1/31
    vrf: BLUE-C2
    encapsulation:
      dot1q:
        vlan: 102
  Ethernet1.103:
    description: to WAN-OBS-01 Ethernet2.103 - BLUE-C3
    mtu: 1500
    ip_address: 10.1.3.1/31
    vrf: BLUE-C3
    encapsulation:
      dot1q:
        vlan: 103

  Ethernet2:
    description: to TLS-CORE-01 Ethernet1
    type: routed
  Ethernet2.101:
    description: to TLS-CORE-01 Ethernet1.101 - BLUE-C1
    mtu: 1500
    ip_address: 10.1.1.2/31
    vrf: BLUE-C1
    encapsulation:
      dot1q:
        vlan: 101
    ospf_network_point_to_point: true
    ospf_area: 0.0.0.0
  Ethernet2.102:
    description: to TLS-CORE-01 Ethernet1.102 - BLUE-C2
    mtu: 1500
    ip_address: 10.1.2.2/31
    vrf: BLUE-C2
    encapsulation:
      dot1q:
        vlan: 102
    ospf_network_point_to_point: true
    ospf_area: 0.0.0.0
  Ethernet2.103:
    description: to WAN-OBS-01 Ethernet2.103 - BLUE-C3
    mtu: 1500
    ip_address: 10.1.3.2/31
    vrf: BLUE-C3
    encapsulation:
      dot1q:
        vlan: 103
    ospf_network_point_to_point: true
    ospf_area: 0.0.0.0

  Ethernet8:
    peer: to TLS WELCOME 02
    peer_interface: Ethernet8
    description: to TLS WELCOME 02 - Ethernet8
    channel_group:
      id: 8
      mode: active

loopback_interfaces:
  Loopback0:
    description: WELCOME ROUTER 01
    ip_address: 1.0.1.1/32
  Loopback101:
    description: WELCOME 01 - BLUE-C1
    vrf: BLUE-C1
    ip_address: 101.0.1.1/32
    ospf_area: 0.0.0.0

management_interfaces:
  Management1:
    description: oob_management
    vrf: MGMT
    ip_address: '{{ ansible_host }}/24'
    gateway: 10.73.254.253

static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.73.254.253

router_ospf:
  process_ids:
    101:
      vrf: BLUE-C1
      passive_interface_default: true
      router_id: 1.0.1.1
      log_adjacency_changes_detail: true
      bfd_enable: false
      no_passive_interfaces:
        - Ethernet2.101

router_bgp:
  as: 65001
  router_id: 1.0.1.1
  bgp_defaults:
    - no bgp default ipv4-unicast
    - distance bgp 20 200 200
    - graceful-restart restart-time 300
    - graceful-restart
  peer_groups:
    OBS_WAN:
      type: ipv4
      description: 'BGP Connection to OBS WAN CPE'
      remote_as: 65000
    WELCOME_ROUTERS:
      type: ipv4
      description: 'BGP Connection to WELCOME ROUTER 02'
      remote_as: 65001
    SEDI:
      type: ipv4
      description: 'BGP Connection to OBS WAN CPE'
      remote_as: 65003
      update_source: Loopback101
      ebgp_multihop: 10
  address_family_ipv4:
    peer_groups:
      OBS_WAN:
        activate: true
      WELCOME_ROUTERS:
        activate: true
      SEDI:
        activate: true
  vrfs:
    BLUE-C1:
      rd: 1.0.1.1:101
      neighbors:
        10.1.1.0:
          peer_group: OBS_WAN
        10.255.1.1:
          peer_group: WELCOME_ROUTERS
        101.0.3.1:
          peer_group: SEDI
