# ---------------------------#
#  Local Authentication
# ---------------------------#

inetsix_aaa_authorization:
  exec:
    default: local

# ---------------------------#
#  Radius Authentication
# ---------------------------#

# inetsix_aaa_authorization:
#   exec:
#     default: group radius local
#   commands:
#     all_default: group radius local

# inetsix_aaa_authentication:
#   login:
#     default: group radius local
#     console: local
#   enable:
#     default: group radius local
#   policies:
#     on_failure_log: true
#     on_success_log: false
#     local:
#       allow_nopassword: true

# inetsix_ip_radius_source_interfaces:
#   - name: Management0
#     vrf: "{{ default_mgmt_interface_vrf }}"

# inetsix_aaa_server_groups:
#   - name: LAB_AAA
#     type: radius
#     servers:
#       - server: 10.73.252.252
#         vrf: "{{ default_mgmt_interface_vrf }}"

# inetsix_radius_servers:
#   - host: 10.73.252.252
#     vrf: "{{ default_mgmt_interface_vrf }}"
#     key: 14031718180D242C757A60