---
# Validation lab


# Cloud Vision server information
daemon_terminattr:
  cvaddrs:
    - 10.73.1.238:9910
  cvauth:
    method: token
    token_file: "/tmp/token"
  cvobscurekeyfile: false
  cvsourceip: '{{ ansible_host }}'
  cvvrf: "{{ default_mgmt_interface_vrf }}"
  cvgnmi: true
  disable_aaa: false
  ingestexclude: '/Sysdb/cell/1/agent,/Sysdb/cell/2/agent'
  smashexcludes: 'ale,flexCounter,hardware,kni,pulse,strata'

# OOB Management network default gateway.
mgmt_gateway: '{{ default_mgt_gateway }}'
mgmt_interface_vrf: "{{ default_mgmt_interface_vrf }}"

# dns servers.
name_servers:
  - 10.73.1.251
  - 10.73.1.252

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
ntp:
  # local_interface:
  #   name: Management1
  #   vrf: MGMT
  servers:
  - name: 10.73.1.254
    vrf: MGMT
    preferred: true

# Clock timezone | Optional
timezone: Europe/Paris

snmp_server:
  communities:
    inetsix-ro:
      access: rw
      access_list_ipv4:
        name: inetsix-snmp-acl
      view: test

validate_state_markdown_flavor: github

custom_structured_configuration_prefix: [ inetsix_, gnmi_, custom_structured_configuration_ ]
