gnmi_access_lists:
  ACL_GNMI:
    sequence_numbers:
      10:
        action: "remark ACL to restrict access to GNMI service"
      20:
        action: "permit ip 10.0.0.0/8 any"

management_api_gnmi:
  enable_vrfs:
    MGMT:
      access_group: ACL_GNMI
    default:
  octa: