---
port_profiles:
  TENANT-A-PR01:
    mode: trunk
    vlans: "110-111"

servers:
  SRV-POD01:
    rack: POD01
    adapters:
      - type: nic
        server_ports: [Eth1]
        switch_ports: [Ethernet3]
        switches: [AVD2-AGG01]
        profile: 'TENANT-A-PR01'
  SRV-POD02:
    rack: POD02
    adapters:
      - type: nic
        server_ports: [Eth01]
        switch_ports: [Ethernet3]
        switches: [AVD2-AGG02]
        profile: 'TENANT-A-PR01'
