dc_name : DC1   # data center name

max_super_spines: 4  # maximum number of super-spines, changing this parameter affects address allocation

super_spine:
  platform: vEOS-LAB  # super-spine platform
  bgp_as: 65001
  spine_interfaces:
    - [ Ethernet1, Ethernet2, Ethernet3, Ethernet4 ]
    - [ Ethernet5, Ethernet6, Ethernet7, Ethernet8 ]
  nodes:
    DC1-SUPER-SPINE1:  # super-spine name
      id: 1
      mgmt_ip: 192.168.0.1/24
    DC1-SUPER-SPINE2:  # super-spine name
      id: 2
      mgmt_ip: 192.168.0.2/24

# IP address range for loopbacks for all super-spines in the DC,
# assigned as /32s
# Assign range larger then total super-spines
super_spine_loopback_network_summary: 192.168.100.0/24


########### BUGFIX for documentation bug where it looks here for this summary #################
super_spine_underlay_p2p_network_summary: 172.31.1.0/24


# additional lines for super-spine BGP config
super_spine_bgp_defaults:
  #  - update wait-for-convergence
  #  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="


overlay_controller:
  platform: vEOS-LAB
  defaults:
#   remote_switches: [DC1-POD1-LEAF1A, DC1-POD1-LEAF1B]
    uplink_to_remote_switches: [Ethernet1, Ethernet2]
    bgp_as: 65100
  nodes:
    DC1-RS1:
      id: 1
      mgmt_ip: 10.73.1.11/16
      remote_switches: [DC1-POD1-LEAF1A, DC1-POD1-LEAF1B]
      remote_switches_interfaces: [Ethernet20, Ethernet20]
    DC1-RS2:
      id: 2
      mgmt_ip: 10.73.1.12/16
      remote_switches: [DC1-POD2-LEAF1A, DC1-POD2-LEAF1B]
      remote_switches_interfaces: [Ethernet20, Ethernet20]
 
overlay_controller_p2p_network_summary: 172.32.255.0/24
overlay_controller_loopback_network_summary: 172.32.250.0/24

max_overlay_controller_to_switch_links: 1

overlay_controller_bgp_defaults:
  #  - update wait-for-convergence
  #  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart


# Update p2p mtu 9000 -> 1500
p2p_uplinks_mtu: 1500

# Adjust default bfd values
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3
