---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: DC1_POD1
pod_number: 1

# Point to Point Network Summary range, assigned as /31 for each
# uplink interfaces
# Assign range larger then total
# [ max_spines_in_a_POD * max_super_spines * max_spine_to_super_spine_links * 2 ]
super_spine_underlay_p2p_network_summary: 172.31.1.0/24

# Point to Point Network Summary range, assigned as /31 for each
# uplink interfaces
# Assign range larger then total [spines * total potential leafs * 2]
underlay_p2p_network_summary: 172.31.255.0/24

# IP address range for evpn loopback for all switches in fabric,
# assigned as /32s
# Assign range larger then total spines + total leafs switches
overlay_loopback_network_summary: 192.168.255.0/24

# VTEP VXLAN Tunnel source loopback IP for leaf switches, assigned in /32s
# Assign range larger then total leaf switches
vtep_loopback_network_summary: 192.168.254.0/24

# mlag pair IP assignment - assign blocks - Assign range larger then
# total leafs switches
mlag_ips:
  leaf_peer_l3: 10.255.254.0/24
  mlag_peer: 10.255.252.0/24


# Enable vlan aware bundles
vxlan_vlan_aware_bundles: false

# Spine Switches
spine:
  platform: vEOS-LAB
  bgp_as: 65100
  uplinks_to_super_spine_interfaces: [Ethernet1, Ethernet6]
  # defines the range of acceptable remote ASNs from leaf switches
  #leaf_as_range: 65101-65132
  nodes:
    DC1-POD1-SPINE1:
      id: 1
      mgmt_ip: 192.168.0.10/24
      # super-spine interfaces to spines
      # taking `max_spine_to_super_spine_links` into account
      # for example: super-spine1, super-spine2, super-spine3, ...
      # or super-spine1, super-spine1, super-spine2, super-spine2, etc.
      super_spine_interfaces: ['Ethernet1', 'Ethernet1']
    DC1-POD1-SPINE2:
      id: 2
      mgmt_ip: 192.168.0.11/24
      # super-spine interfaces to spines
      # taking `max_spine_to_super_spine_links` into account
      # for example: super-spine1, super-spine2, super-spine3, ...
      # or super-spine1, super-spine1, super-spine2, super-spine2, etc.
      super_spine_interfaces: ['Ethernet2', 'Ethernet2']

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    # virtual router mac for VNIs assigned to Leaf switches
    # format: xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:dc:01
    platform: vEOS-LAB
    #bgp_as: 65100
    spines: [DC1-POD1-SPINE1, DC1-POD1-SPINE2]
    uplink_to_spine_interfaces: [Ethernet2, Ethernet3]
    mlag_interfaces: [Ethernet1, Ethernet6]
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
    DC1_POD1_LEAF1:
      bgp_as: 65101
      filter:
        tenants:
          - Tenant_A
      nodes:
        DC1-POD1-LEAF1A:
          id: 1
          mgmt_ip: 192.168.0.12/24
          spine_interfaces: [Ethernet2, Ethernet2]
        DC1-POD1-LEAF1B:
          id: 2
          mgmt_ip: 192.168.0.13/24
          spine_interfaces: [Ethernet3, Ethernet3]
    DC1_POD1_LEAF2:
      bgp_as: 65102
      filter:
        tenants:
          - Tenant_C
      nodes:
        DC1-POD1-LEAF2A:
          id: 3
          mgmt_ip: 192.168.0.14/24
          spine_interfaces: [Ethernet4, Ethernet4]
        DC1-POD1-LEAF2B:
          id: 4
          mgmt_ip: 192.168.0.15/24
          spine_interfaces: [Ethernet5, Ethernet5]

l2leaf:
  defaults:
    platform: vEOS-LAB
#    parent_l3leafs: [ DC1-POD1-LEAF1A, DC1-POD1-LEAF1B ]
    uplink_interfaces: [ Ethernet1, Ethernet2 ]
    mlag_interfaces: [ Ethernet3, Ethernet4 ]
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
  node_groups:
    DC1_POD1_L2LEAF1:
      parent_l3leafs: [ DC1-POD1-LEAF1A, DC1-POD1-LEAF1B ]
      filter:
        tenants: [ Tenant_A ]
        tags: [ opzone, web, app ]
      nodes:
        DC1-POD1-L2LEAF1A:
          id: 5
          mgmt_ip: 192.168.0.21/24
          l3leaf_interfaces: [ Ethernet7, Ethernet7 ]
    DC1_POD1_L2LEAF2:
      parent_l3leafs: [ DC1-POD1-LEAF2A, DC1-POD1-LEAF2B ]
      filter:
        tenants: [ Tenant_A ]
        tags: [ opzone, web, app ]
      nodes:
        DC1-POD1-L2LEAF2A:
          id: 7
          mgmt_ip: 192.168.0.22/24
          l3leaf_interfaces: [ Ethernet7, Ethernet7 ]

#### Override for vEOS Lab Caveats ####

# Disable update wait-for-convergence and update wait-for-install,
# which is not supported in vEOS-LAB.
# Refer to design guide

spine_bgp_defaults:
  #  - update wait-for-convergence
  #  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

leaf_bgp_defaults:
  #  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

