ztp:
  default:
    registration: http://10.73.255.1/ztp/bootstrap
    use_system_mac: true
  general:
    subnets:
      - network: 10.73.255.0
        netmask: 255.255.255.0
        start: 10.73.255.200
        end: 10.73.255.210
        lease_time: 300

  clients:
    # edge
    - name: DC1-AGG01
      mac: '0c:1d:c0:1d:62:01'
      ip4: 10.73.255.121
    - name: DC1-AGG02
      mac: '0c:1d:c0:1d:62:01'
      ip4: 10.73.255.122
    # l3leaf
    - name: DC1-LEAF1A
      mac: '0c:1d:c0:1d:62:01'
      ip4: 10.73.255.111
    - name: DC1-LEAF1B
      mac: '0c:1d:c0:1d:62:01'
      ip4: 10.73.255.112
    - name: DC1-LEAF2B
      mac: '0c:1d:c0:1d:62:01'
      ip4: 10.73.255.114
    - name: DC1-LEAF3A
      mac: '0c:1d:c0:1d:62:01'
      ip4: 10.73.255.117
    - name: DC1-LEAF4A
      mac: '0c:1d:c0:1d:62:01'
      ip4: 10.73.255.118
    # spine
    - name: DC1-SPINE1
      mac: '0c:1d:c0:1d:62:01'
      ip4: 10.73.255.101
    - name: DC1-SPINE2
      mac: '0c:1d:c0:1d:62:01'
      ip4: 10.73.255.102
