---
# On mlag leafs, an SVI interface is defined per vrf, to establish iBGP peering. | Required (when mlag leafs in topology)
# The SVI id will be derived from the base vlan defined: mlag_ibgp_peering_vrfs.base_vlan + vrf_vni
mlag_ibgp_peering_vrfs:
  base_vlan: 3000

# Specify RD type | Optional
# Route Distinguisher (RD) for L2 / L3 services is set to <overlay_loopback>:<vni> per default.
# By configuring evpn_rd_type the Administrator subfield (first part of RD) can be set to other values.
#
# Note:
# RD is a 48-bit value which is split into <16-bit>:<32-bit> or <32-bit>:<16-bit>.
# For loopback or 32-bit ASN/number the VNI can only be a 16-bit number.
# For 16-bit ASN/number the VNI can be a 32-bit number.
# evpn_rd_type:
#   # admin_subfield: < "overlay_loopback" | "vtep_loopback" | "leaf_asn" | "spine_asn" | < IPv4 Address > | <0-65535> | <0-4294967295> | default -> "overlay_loopback" >
#   admin_subfield: vtep_loopback

# Specify RT type | Optional
# Route Target (RT) for L2 / L3 services is set to <vni>:<vni> per default
# By configuring evpn_rt_type the Administrator subfield (first part of RT) can be set to other values.
#
# Note:
# RT is a 48-bit value which is split into <16-bit>:<32-bit> or <32-bit>:<16-bit>.
# For 32-bit ASN/number the VNI can only be a 16-bit number.
# For 16-bit ASN/number the VNI can be a 32-bit number.
evpn_rt_type:
  # admin_subfield: < "leaf_asn" | "spine_asn" | "vni" | <0-65535> | <0-4294967295> | default -> "vni" >
  admin_subfield: vni

# SVI Profile
svi_profiles:
  GENERIC:
    mtu: 1560
    enabled: true
  GENERIC_FULL:
    name: GENERIC Name
    mtu: 1560
    enabled: false
    ip_address_virtual: 10.1.10.254/24
  WITH_NO_MTU:
    enabled: true
  WITH_DHCP_01_SNOOPING:
    enabled: true
    ip_address_virtual: 10.1.11.254/24
    igmp_snooping_enabled: false
    ip_helpers:
      1.1.1.1:
        source_interface: lo100
        source_vrf: TEST
  WITH_DHCP_02:
    tags: ['DC1']
    enabled: true
    ip_helpers:
      1.1.1.1:
        source_interface: lo100
        source_vrf: MGMT

# DC1 Tenants Networks
# Documentation of Tenant specific information - Vlans/VRFs
tenants:
  # Tenant A Specific Information - VRFs / VLANs
  Tenant_A:
    mac_vrf_vni_base: 10000
    enable_mlag_ibgp_peering_vrfs: true
    vrfs:
      TENANT_A_PROJECT01:
        vrf_vni: 11
        static_routes:
          - destination_address_prefix: 1.1.1.0/24
            gateway: 10.1.10.1
            nodes: ['EAPI-BL01A', 'EAPI-BL01B']
        redistribute_static: true
        svis:
          110:
            name: 'PR01-DEMO'
            tags: ['DC1']
            enabled: true
            ip_address_virtual: 10.1.10.254/24
            # igmp_snooping: false
          111:
            name: 'PR01-TRUST'
            tags: ['POD01', 'POD02']
            profile: 'WITH_DHCP_01_SNOOPING'
          112:
            name: 'PR01-TRUST'
            tags: ['POD01', 'POD02']
            ip_address_virtual: 10.1.12.254/24
            igmp_snooping_enabled: false
          113:
            name: 'PR01-DMZ'
            tags: [POD03]
            enabled: true
            ip_address_virtual: 10.1.13.254/24
            igmp_snooping_enabled: true
      #     311:
      #       name: 'PR01-TRUST-DHCP'
      #       tags: ['DC1']
      #       enabled: true
      #       ip_address_virtual: 10.3.11.254/24
      #       igmp_snooping_enabled: true
      #       ip_helpers:
      #         1.1.1.1:
      #           source_interface: lo100
      # TENANT_A_PROJECT02:
      #   ip_helpers:
      #     1.1.1.1:
      #       source_interface: lo100
      #   vrf_vni: 12
      #   vtep_diagnostic:
      #     loopback: 100
      #     loopback_ip_range: 10.2.255.0/24
      #   svis:
      #     114:
      #       name: 'PR02-DMZ'
      #       tags: ['POD01']
      #       enabled: true
      #       ip_address_virtual: 10.2.12.254/24
      #       igmp_snooping: true

# Tenant D Specific Information - Pure L2 tenant
  Tenant_B:
    mac_vrf_vni_base: 20000
    enable_mlag_ibgp_peering_vrfs: true
    l2vlans:
      201:
        name: 'B-ELAN-201'
        tags: ['DC1']
        igmp_snooping: false
