---
node_type_keys:
  spine:
    type: spine
    connected_endpoints: false
    default_evpn_role: non
    mlag_support: true
    network_services:
      l2: true
      l3: true
    vtep: false
    underlay_router: false
    uplink_type: 'port-channel'

  l2leaf:
    type: l2leaf
    connected_endpoints: true
    default_evpn_role: non
    mlag_support: true
    network_services:
      l2: true
      l3: false
    vtep: false
    uplink_type: 'port-channel'
    underlay_router: false
