---
servers:
  SRV-POD01:
    rack: POD01
    adapters:
      - type: nic
        server_ports: [Eth1]
        switch_ports: [Ethernet3]
        switches: [EAPI-AGG01]
        profile: ALL
  SRV-POD02:
    rack: POD02
    adapters:
      - type: nic
        server_ports: [Eth1]
        switch_ports: [Ethernet3]
        switches: [EAPI-AGG02]
        profile: ALL
  SRV-POD03:
    rack: POD03
    adapters:
      - server_ports: [ Eth1, Eth2 ]
        switch_ports: [ Ethernet5, Ethernet5 ]
        switches: [ EAPI-LEAF3A, EAPI-LEAF4A ]
        profile: ALL
        port_channel:
          state: present
          description: PortChanne1
          mode: active
          short_esi: '0303:0202:0101'
