vlans:
  110:
    tenant: Tenant_A
    name: PR01-DEMO
  111:
    tenant: Tenant_A
    name: PR01-TRUST
  112:
    tenant: Tenant_A
    name: PR01-TRUST
  201:
    tenant: Tenant_B
    name: B-ELAN-201