l3_edge:
  p2p_links_ip_pools:
    dci_evpn_gateway: 172.31.252.0/24
  p2p_links:
    - id: 1
      ip_pool: dci_evpn_gateway
      nodes: [avd-leaf3a, srv-pod03]
      interfaces: [Ethernet5 , Ethernet1]
      as: [65103, 65300]
      include_in_underlay_protocol: true
    - id: 2
      ip_pool: dci_evpn_gateway
      nodes: [avd-leaf4a, srv-pod03]
      interfaces: [Ethernet5 , Ethernet2]
      as: [65104, 65300]
      include_in_underlay_protocol: true