vrfs:
  MGMT:
    ip_routing: false
  tenant_a_110:
    ip_routing: true
    ipv6_routing: false
  tenant_a_113:
    ip_routing: true
    ipv6_routing: false
  tenant_b_201:
    ip_routing: true
    ipv6_routing: false

loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 192.168.255.203/32
  Loopback1:
    description: VTEP_VXLAN_Tunnel_Source
    shutdown: false
    ip_address: 192.168.254.203/32

ethernet_interfaces:
  # Layer 3 fot EVPN Gateway
  Ethernet1:
    peer: avd-leaf3a
    peer_interface: Ethernet5
    peer_type: other
    description: P2P_LINK_TO_avd-leaf3a_Ethernet5
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: 172.31.252.1/31

  Ethernet2:
    peer: avd-leaf4a
    peer_interface: Ethernet5
    peer_type: other
    description: P2P_LINK_TO_avd-leaf4a_Ethernet5
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: 172.31.252.3/31

  # Layer 2 for ESI
  Ethernet3:
    description: to AVD2-LEAF3A - eth5
    shutdown: false
    logging:
      event:
        link_status: true
    channel_group:
      id: 1
      mode: active
  Ethernet4:
    description: to AVD2-LEAF4A - eth5
    shutdown: false
    logging:
      event:
        link_status: true
    channel_group:
      id: 1
      mode: active

port_channel_interfaces:
  Port-Channel1:
    description: 'to AVD2-LEAF{3|4}A - ESI'
    type: switched
    vlans: "1-4000"
    native_vlan: 1
    mode: trunk
    spanning_tree_bpdufilter: false
    spanning_tree_bpduguard: false
    spanning_tree_portfast: edge

vlan_interfaces:
  Vlan110:
    description: SVI for Tenant A vlan 110
    shutdown: false
    vrf: tenant_a_110
    ip_address: 10.1.10.3/24
  Vlan113:
    description: SVI for Tenant A vlan 113
    shutdown: false
    vrf: tenant_a_113
    ip_address: 10.1.13.3/24
  Vlan201:
    description: SVI for Tenant B vlan 201
    shutdown: false
    vrf: tenant_b_201
    ip_address: 10.2.1.3/24

static_routes:
  - vrf: tenant_a_110
    destination_address_prefix: 0.0.0.0/0
    gateway: 10.1.10.254
  - vrf: tenant_a_113
    destination_address_prefix: 0.0.0.0/0
    gateway: 10.1.13.254