---
- name: Build Switch configuration
  hosts: [all]
  collections:
    - arista.avd
    - arista.cvp
    - arista.eos
  tasks:
    # - name: build local folders
    #   tags: [init, build]
    #   import_role:
    #     name: build_output_folders
      # vars:
      #   fabric_dir_name: '{{fabric_name}}'
    - name: generate intended variables
      tags: [build]
      import_role:
        name: eos_designs

    - name: generate device intended config and documentation
      tags: [build]
      import_role:
        name: eos_cli_config_gen

    - name: deploy configuration to device
      tags: [deploy, never]
      import_role:
        name: arista.avd.eos_config_deploy_eapi


- name: Build Endpoints configuration
  hosts: ['ENDPOINTS']
  collections:
    - arista.avd
    - arista.cvp
    - arista.eos
  tasks:
    - name: generate device intended config and documentation
      tags: [build]
      import_role:
        name: eos_cli_config_gen

    - name: deploy configuration to device
      tags: [deploy, never]
      import_role:
        name: arista.avd.eos_config_deploy_eapi