---
- name: Build Switch configuration
  hosts: DC1_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: build local folders
      tags: [l3ls_evpn]
      import_role:
        name: build_output_folders
    - name: generate intented variables
      tags: [l3ls_evpn]
      import_role:
        name: eos_l3ls_evpn
    - name: generate device intended config and documention
      tags: [never,cli_config_gen]
      import_role:
        name: eos_cli_config_gen
