---
- name: Audit Switch State based on AVD
  hosts: all
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: deploy configuration to device
      import_role:
         name: arista.avd.eos_validate_state
