---
- name: Build Switch configuration
  hosts: EAPI_FABRIC
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: build local folders
      tags: [init]
      import_role:
        name: build_output_folders
      vars:
        fabric_dir_name: '{{fabric_name}}'
    - name: generate intented variables
      tags: [build]
      import_role:
        name: eos_l3ls_evpn
    - name: update device intended config with DCI
      tags: [build]
      import_role:
         name: eos_dci
    - name: generate device intended config and documention
      tags: [build]
      import_role:
        name: eos_cli_config_gen
    - name: deploy configuration to device
      tags: [deploy, never]
      import_role:
         name: arista.avd.eos_config_deploy_eapi
