---
- name: Build Switch configuration
  hosts: cv_server
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  vars:
    CVP_CONFIGLETS:
      01TRAINING-alias: "alias a101 show version"
      01TRAINING-01: "alias a102 show version"
  tasks:
    - name: "Gather CVP facts {{inventory_hostname}}"
      arista.cvp.cv_facts:
        facts:
          configlets
      register: CVP_FACTS

    - name: "Configure configlet on {{inventory_hostname}}"
      arista.cvp.cv_configlet:
        cvp_facts: "{{CVP_FACTS.ansible_facts}}"
        configlets: "{{CVP_CONFIGLETS}}"
        configlet_filter: ["TRAINING"]
        state: present
      register: CVP_CONFIGLET_RESULT

    - name: "Print logs"
      debug:
        msg: "{{ CVP_CONFIGLET_RESULT }}"