---
- name: cv_configlet unit testing
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: "Gather CVP facts {{inventory_hostname}}"
      arista.cvp.cv_facts_v3:
      register: CVP_FACTS

    - name: "Print logs"
      debug:
        msg: "{{ CVP_FACTS }}"