---
- name: Configure ZTP service on CloudVision
  hosts: ZTP
  gather_facts: true
  tasks:
    - name: 'Execute ZTP configuration role'
      import_role:
        name: arista.cvp.dhcp_configuration
