---
- name: Configure DHCP Service for ZTP
  hosts: cv_ztp
  gather_facts: false
  tasks:
    - name: 'Execute DHCP configuration role'
      import_role:
        name: arista.cvp.dhcp_configuration
      vars:
        mode: offline
        output_dirs: '{{inventory}}'
