---
- name: Populate Netbox from AVD
  hosts: EAPI_FABRIC
  connection: local
  gather_facts: False
  collections:
    - arista.avd
    - netbox.netbox
    - inetsix.avd_tools
  tasks:
    - name: "AVD populated on Netbox {{ inventory_hostname }}"
      import_role:
        name: inetsix.avd_tools.eos_netbox_provisioner
      vars:
        netbox_fabric_group: EAPI_FABRIC
        netbox_svc_group: EAPI_SERVICES
