---
- name: Upload configlet
  hosts: cv_server
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  vars:
    CVP_CONFIGLETS:
      01DEMO-alias: "alias a{{ 999 | random }} show version"
      01DEMO-01: "alias a{{ 999 | random }} show version"
      01DEMO-02: "alias sib show interface brief"
      01DEMO-03: "{{lookup('file', '../configlets/DEVICE-ALIASES.conf')}}"

  tasks:
    - name: "Gather CVP facts {{inventory_hostname}}"
      arista.cvp.cv_facts:
        facts:
          configlets
      register: CVP_FACTS

    - name: "Configure configlet on {{inventory_hostname}}"
      arista.cvp.cv_configlet:
        cvp_facts: "{{CVP_FACTS.ansible_facts}}"
        configlets: "{{CVP_CONFIGLETS}}"
        configlet_filter: ["DEMO"]
        state: present
      register: CVP_CONFIGLET_RESULT