- name: Device Management in Cloudvision
  hosts: cv_server
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  vars:
    CVP_DEVICES:
      DC1-SPINE1:
        name: 'DC1-SPINE1'
        parentContainerName: DC1_SPINES
        configlets:
          - 'AVD_DC1-SPINE1'
          - '01TRAINING-01'
        imageBundle: []  # Not yet supported
  tasks:
    - name: "Gather CVP facts {{inventory_hostname}}"
      arista.cvp.cv_facts:
      register: CVP_FACTS
    - name: "Configure devices on {{inventory_hostname}}"
      arista.cvp.cv_device:
        devices: "{{CVP_DEVICES}}"
        cvp_facts: '{{CVP_FACTS.ansible_facts}}'
        device_filter: ['DC1-SPINE1']
        state: present
      register: CVP_DEVICES_RESULTS
    - name: 'Display debug'
      debug:
        msg: '{{CVP_DEVICES_RESULTS}}'
