- name: Cloudvision v3 test playbook
  hosts: cv_server
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  vars:
    execute_tasks: true
    CVP_DEVICES:
      - fqdn: CV-ANSIBLE-EOS01
        # systemMacAddress: '50:8d:00:e3:78:aa'
        parentContainerName: 'ANSIBLE'
        configlets:
            - '01TRAINING-01'

    CVP_CONTAINERS:
      DC2:
        parentContainerName: Tenant
      Leafs:
        parentContainerName: DC2
      Spines:
        parentContainerName: DC2
        configlets:
          - '01TRAINING-01'
      POD01:
        parentContainerName: Leafs

    CVP_CONFIGLETS:
      01TRAINING-alias: "alias a101 show version"
      01TRAINING-01: "alias a102 show version"

    CVP_CONFIGLETS_2:
      01TRAINING-alias: "alias a103 show version"
      01TRAINING-01: "alias a102 show version"

  tasks:
    # --------------------
    # CONFIGLETS
    # --------------------
    - name: "Configure configlet on {{inventory_hostname}}"
      tags: [full, configlet, configlet_create]
      arista.cvp.cv_configlet_v3:
        configlets: "{{CVP_CONFIGLETS}}"
        state: present
      register: CVP_CONFIGLET_RESULT
    - name: "Print logs"
      tags: [full, configlet, configlet_create]
      debug:
        msg: "{{ CVP_CONFIGLET_RESULT }}"

    - name: Pause for 60 secondss to review on CV
      tags: [full, configlet]
      pause:
        seconds: 60

    - name: "Configure configlet on {{inventory_hostname}}"
      tags: [full, configlet, configlet_update]
      arista.cvp.cv_configlet_v3:
        configlets: "{{CVP_CONFIGLETS_2}}"
        state: present
      register: CVP_CONFIGLET_RESULT
    - name: "Print logs"
      tags: [full, configlet, configlet_update]
      debug:
        msg: "{{ CVP_CONFIGLET_RESULT }}"

    - name: Pause for 60 secondss to review on CV
      tags: [full, configlet]
      pause:
        seconds: 60

    - name: "Configure configlet on {{inventory_hostname}}"
      tags: [full, configlet, configlet_delete]
      arista.cvp.cv_configlet_v3:
        configlets: "{{CVP_CONFIGLETS}}"
        state: absent
      register: CVP_CONFIGLET_RESULT
    - name: "Print logs"
      tags: [full, configlet, configlet_delete]
      debug:
        msg: "{{ CVP_CONFIGLET_RESULT }}"

    - name: Pause for 60 secondss to review on CV
      tags: [full]
      pause:
        seconds: 60

    - name: "Execute pending tasks on {{ inventory_hostname }}"
      tags: [full, configlet, configlet_delete, configlet_create, configlet_update]
      arista.cvp.cv_task_v3:
        tasks: "{{ CVP_CONFIGLET_RESULT.taskIds }}"
        # wait: 60
      when:
        - execute_tasks|bool

    # --------------------
    # CONTAINERS
    # --------------------
    - name: 'running cv_container_v3 in present on {{inventory_hostname}}'
      tags: [full, container_add]
      arista.cvp.cv_container_v3:
        topology: "{{CVP_CONTAINERS}}"
        state: present
      register: RESULT
    - name: Display result
      tags: [full, container_add]
      debug:
        msg: '{{RESULT}}'

    - name: Pause for 60 secondss to review on CV
      tags: [full, container]
      pause:
        seconds: 60

    - name: 'running cv_container_v3 with absent on {{inventory_hostname}}'
      tags: [full, container, container_delete]
      arista.cvp.cv_container_v3:
        topology: "{{CVP_CONTAINERS}}"
        state: absent
      register: RESULT
    - name: Display result
      tags: [full, container, container_delete]
      debug:
        msg: '{{RESULT}}'

    # --------------------
    # DEVICES
    # --------------------
    - name: "Configure devices on {{inventory_hostname}}"
      tags: [full, device]
      arista.cvp.cv_device_v3:
        devices: "{{CVP_DEVICES}}"
        state: present
      register: CVP_DEVICES_RESULTS
    - name: 'Display debug'
      tags: [full, device]
      debug:
        msg: '{{CVP_DEVICES_RESULTS}}'