- name: Cloudvision v3 test playbook
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  vars:
    CVP_DEVICES:
      - fqdn: tg-cvaas-aawg-ci-cv-unit
        systemMacAddress: '50:01:00:e5:e3:6a'
        serialNumber: 64793E1D3DE2240F547E5964354214A4
        parentContainerName: 'tg-lab'
        configlets:
            - 'tg-generic-aliases'
            - 'tg-cvaas-aawg-ci-cv-unit'

  tasks:
    # --------------------
    # DEVICES
    # --------------------
    - name: "Configure devices on {{inventory_hostname}}"
      arista.cvp.cv_device_v3:
        devices: "{{CVP_DEVICES}}"
        state: present
        apply_mode: strict
        search_key: serialNumber
      register: CVP_DEVICES_RESULTS

    - name: 'Display debug'
      debug:
        msg: '{{CVP_DEVICES_RESULTS}}'