CVP_CONFIGLETS:
  AVD_DC1-LEAF1A: "!RANCID-CONTENT-TYPE: arista\n!\ndaemon TerminAttr\n   exec /usr/bin/TerminAttr\
    \ -cvaddr=10.73.254.1:9910 -cvvrf=MGMT -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata\
    \ -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -taillogs\n   no shutdown\n\
    !\nvlan internal order ascending range 1006 1199\n!\ntransceiver qsfp default-mode\
    \ 4x10G\n!\nservice routing protocols model multi-agent\n!\nhostname DC1-LEAF1A\n\
    ip name-server vrf MGMT 10.73.1.254\nip name-server vrf MGMT 10.73.254.253\n!\n\
    snmp-server community inetsix-ro view test rw inetsix-snmp-acl\n!\nspanning-tree\
    \ mode mstp\nno spanning-tree vlan-id 4094\nspanning-tree mst 0 priority 4096\n\
    !\naaa authorization exec default local\n!\nno aaa root\nno enable password\n\
    !\nusername admin privilege 15 role network-admin nopassword\nusername ansible\
    \ privilege 15 role network-admin secret sha512 $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/\n\
    username cvpadmin privilege 15 role network-admin secret sha512 $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.\n\
    username demo privilege 15 role network-admin secret sha512 $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/\n\
    !\nclock timezone Europe/Paris\n!\nvlan 4094\n   name MLAG_PEER\n   trunk group\
    \ MLAG\n!\nvrf instance MGMT\n!\ninterface Port-Channel1\n   description DC1-SPINE1_Po1\n\
    \   no shutdown\n   switchport\n   switchport mode trunk\n   mlag 1\n!\ninterface\
    \ Port-Channel7\n   description MLAG_PEER_DC1-LEAF1B_Po7\n   no shutdown\n   switchport\n\
    \   switchport trunk allowed vlan 2-4094\n   switchport mode trunk\n   switchport\
    \ trunk group MLAG\n!\ninterface Ethernet1\n   description DC1-SPINE1_Ethernet1\n\
    \   no shutdown\n   channel-group 1 mode active\n!\ninterface Ethernet2\n   description\
    \ DC1-SPINE2_Ethernet1\n   no shutdown\n   channel-group 1 mode active\n!\ninterface\
    \ Ethernet7\n   description MLAG_PEER_DC1-LEAF1B_Ethernet7\n   no shutdown\n \
    \  channel-group 7 mode active\n!\ninterface Ethernet8\n   description MLAG_PEER_DC1-LEAF1B_Ethernet8\n\
    \   no shutdown\n   channel-group 7 mode active\n!\ninterface Management1\n  \
    \ description oob_management\n   no shutdown\n   vrf MGMT\n   ip address 10.73.254.11/24\n\
    !\ninterface Vlan4094\n   description MLAG_PEER\n   no shutdown\n   mtu 1500\n\
    \   no autostate\n   ip address 172.31.253.0/31\n!\nip routing\nno ip routing\
    \ vrf MGMT\n!\nmlag configuration\n   domain-id DC1_LEAF1\n   local-interface\
    \ Vlan4094\n   peer-address 172.31.253.1\n   peer-link Port-Channel7\n   reload-delay\
    \ mlag 300\n   reload-delay non-mlag 330\n!\nip route vrf MGMT 0.0.0.0/0 10.73.254.253\n\
    !\nmanagement api http-commands\n   protocol https\n   no shutdown\n   !\n   vrf\
    \ MGMT\n      no shutdown\n!\nmanagement ssh\n   idle-timeout 0\n   no shutdown\n\
    \   vrf MGT\n      no shutdown\n!\nend\n"
  AVD_DC1-LEAF1B: "!RANCID-CONTENT-TYPE: arista\n!\ndaemon TerminAttr\n   exec /usr/bin/TerminAttr\
    \ -cvaddr=10.73.254.1:9910 -cvvrf=MGMT -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata\
    \ -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -taillogs\n   no shutdown\n\
    !\nvlan internal order ascending range 1006 1199\n!\ntransceiver qsfp default-mode\
    \ 4x10G\n!\nservice routing protocols model multi-agent\n!\nhostname DC1-LEAF1B\n\
    ip name-server vrf MGMT 10.73.1.254\nip name-server vrf MGMT 10.73.254.253\n!\n\
    snmp-server community inetsix-ro view test rw inetsix-snmp-acl\n!\nspanning-tree\
    \ mode mstp\nno spanning-tree vlan-id 4094\nspanning-tree mst 0 priority 4096\n\
    !\naaa authorization exec default local\n!\nno aaa root\nno enable password\n\
    !\nusername admin privilege 15 role network-admin nopassword\nusername ansible\
    \ privilege 15 role network-admin secret sha512 $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/\n\
    username cvpadmin privilege 15 role network-admin secret sha512 $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.\n\
    username demo privilege 15 role network-admin secret sha512 $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/\n\
    !\nclock timezone Europe/Paris\n!\nvlan 4094\n   name MLAG_PEER\n   trunk group\
    \ MLAG\n!\nvrf instance MGMT\n!\ninterface Port-Channel1\n   description DC1-SPINE1_Po1\n\
    \   no shutdown\n   switchport\n   switchport mode trunk\n   mlag 1\n!\ninterface\
    \ Port-Channel7\n   description MLAG_PEER_DC1-LEAF1A_Po7\n   no shutdown\n   switchport\n\
    \   switchport trunk allowed vlan 2-4094\n   switchport mode trunk\n   switchport\
    \ trunk group MLAG\n!\ninterface Ethernet1\n   description DC1-SPINE1_Ethernet2\n\
    \   no shutdown\n   channel-group 1 mode active\n!\ninterface Ethernet2\n   description\
    \ DC1-SPINE2_Ethernet2\n   no shutdown\n   channel-group 1 mode active\n!\ninterface\
    \ Ethernet7\n   description MLAG_PEER_DC1-LEAF1A_Ethernet7\n   no shutdown\n \
    \  channel-group 7 mode active\n!\ninterface Ethernet8\n   description MLAG_PEER_DC1-LEAF1A_Ethernet8\n\
    \   no shutdown\n   channel-group 7 mode active\n!\ninterface Management1\n  \
    \ description oob_management\n   no shutdown\n   vrf MGMT\n   ip address 10.73.254.12/24\n\
    !\ninterface Vlan4094\n   description MLAG_PEER\n   no shutdown\n   mtu 1500\n\
    \   no autostate\n   ip address 172.31.253.1/31\n!\nip routing\nno ip routing\
    \ vrf MGMT\n!\nmlag configuration\n   domain-id DC1_LEAF1\n   local-interface\
    \ Vlan4094\n   peer-address 172.31.253.0\n   peer-link Port-Channel7\n   reload-delay\
    \ mlag 300\n   reload-delay non-mlag 330\n!\nip route vrf MGMT 0.0.0.0/0 10.73.254.253\n\
    !\nmanagement api http-commands\n   protocol https\n   no shutdown\n   !\n   vrf\
    \ MGMT\n      no shutdown\n!\nmanagement ssh\n   idle-timeout 0\n   no shutdown\n\
    \   vrf MGT\n      no shutdown\n!\nend\n"
  AVD_DC1-LEAF2A: "!RANCID-CONTENT-TYPE: arista\n!\ndaemon TerminAttr\n   exec /usr/bin/TerminAttr\
    \ -cvaddr=10.73.254.1:9910 -cvvrf=MGMT -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata\
    \ -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -taillogs\n   no shutdown\n\
    !\nvlan internal order ascending range 1006 1199\n!\ntransceiver qsfp default-mode\
    \ 4x10G\n!\nservice routing protocols model multi-agent\n!\nhostname DC1-LEAF2A\n\
    ip name-server vrf MGMT 10.73.1.254\nip name-server vrf MGMT 10.73.254.253\n!\n\
    snmp-server community inetsix-ro view test rw inetsix-snmp-acl\n!\nspanning-tree\
    \ mode mstp\nno spanning-tree vlan-id 4094\nspanning-tree mst 0 priority 4096\n\
    !\naaa authorization exec default local\n!\nno aaa root\nno enable password\n\
    !\nusername admin privilege 15 role network-admin nopassword\nusername ansible\
    \ privilege 15 role network-admin secret sha512 $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/\n\
    username cvpadmin privilege 15 role network-admin secret sha512 $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.\n\
    username demo privilege 15 role network-admin secret sha512 $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/\n\
    !\nclock timezone Europe/Paris\n!\nvlan 4094\n   name MLAG_PEER\n   trunk group\
    \ MLAG\n!\nvrf instance MGMT\n!\ninterface Port-Channel1\n   description DC1-SPINE1_Po3\n\
    \   no shutdown\n   switchport\n   switchport mode trunk\n   mlag 1\n!\ninterface\
    \ Port-Channel7\n   description MLAG_PEER_DC1-LEAF2B_Po7\n   no shutdown\n   switchport\n\
    \   switchport trunk allowed vlan 2-4094\n   switchport mode trunk\n   switchport\
    \ trunk group MLAG\n!\ninterface Ethernet1\n   description DC1-SPINE1_Ethernet3\n\
    \   no shutdown\n   channel-group 1 mode active\n!\ninterface Ethernet2\n   description\
    \ DC1-SPINE2_Ethernet3\n   no shutdown\n   channel-group 1 mode active\n!\ninterface\
    \ Ethernet7\n   description MLAG_PEER_DC1-LEAF2B_Ethernet7\n   no shutdown\n \
    \  channel-group 7 mode active\n!\ninterface Ethernet8\n   description MLAG_PEER_DC1-LEAF2B_Ethernet8\n\
    \   no shutdown\n   channel-group 7 mode active\n!\ninterface Management1\n  \
    \ description oob_management\n   no shutdown\n   vrf MGMT\n   ip address 10.73.254.13/24\n\
    !\ninterface Vlan4094\n   description MLAG_PEER\n   no shutdown\n   mtu 1500\n\
    \   no autostate\n   ip address 172.31.253.4/31\n!\nip routing\nno ip routing\
    \ vrf MGMT\n!\nmlag configuration\n   domain-id DC1_LEAF2\n   local-interface\
    \ Vlan4094\n   peer-address 172.31.253.5\n   peer-link Port-Channel7\n   reload-delay\
    \ mlag 300\n   reload-delay non-mlag 330\n!\nip route vrf MGMT 0.0.0.0/0 10.73.254.253\n\
    !\nmanagement api http-commands\n   protocol https\n   no shutdown\n   !\n   vrf\
    \ MGMT\n      no shutdown\n!\nmanagement ssh\n   idle-timeout 0\n   no shutdown\n\
    \   vrf MGT\n      no shutdown\n!\nend\n"
  AVD_DC1-LEAF2B: "!RANCID-CONTENT-TYPE: arista\n!\ndaemon TerminAttr\n   exec /usr/bin/TerminAttr\
    \ -cvaddr=10.73.254.1:9910 -cvvrf=MGMT -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata\
    \ -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -taillogs\n   no shutdown\n\
    !\nvlan internal order ascending range 1006 1199\n!\ntransceiver qsfp default-mode\
    \ 4x10G\n!\nservice routing protocols model multi-agent\n!\nhostname DC1-LEAF2B\n\
    ip name-server vrf MGMT 10.73.1.254\nip name-server vrf MGMT 10.73.254.253\n!\n\
    snmp-server community inetsix-ro view test rw inetsix-snmp-acl\n!\nspanning-tree\
    \ mode mstp\nno spanning-tree vlan-id 4094\nspanning-tree mst 0 priority 4096\n\
    !\naaa authorization exec default local\n!\nno aaa root\nno enable password\n\
    !\nusername admin privilege 15 role network-admin nopassword\nusername ansible\
    \ privilege 15 role network-admin secret sha512 $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/\n\
    username cvpadmin privilege 15 role network-admin secret sha512 $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.\n\
    username demo privilege 15 role network-admin secret sha512 $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/\n\
    !\nclock timezone Europe/Paris\n!\nvlan 4094\n   name MLAG_PEER\n   trunk group\
    \ MLAG\n!\nvrf instance MGMT\n!\ninterface Port-Channel1\n   description DC1-SPINE1_Po3\n\
    \   no shutdown\n   switchport\n   switchport mode trunk\n   mlag 1\n!\ninterface\
    \ Port-Channel7\n   description MLAG_PEER_DC1-LEAF2A_Po7\n   no shutdown\n   switchport\n\
    \   switchport trunk allowed vlan 2-4094\n   switchport mode trunk\n   switchport\
    \ trunk group MLAG\n!\ninterface Ethernet1\n   description DC1-SPINE1_Ethernet4\n\
    \   no shutdown\n   channel-group 1 mode active\n!\ninterface Ethernet2\n   description\
    \ DC1-SPINE2_Ethernet4\n   no shutdown\n   channel-group 1 mode active\n!\ninterface\
    \ Ethernet7\n   description MLAG_PEER_DC1-LEAF2A_Ethernet7\n   no shutdown\n \
    \  channel-group 7 mode active\n!\ninterface Ethernet8\n   description MLAG_PEER_DC1-LEAF2A_Ethernet8\n\
    \   no shutdown\n   channel-group 7 mode active\n!\ninterface Management1\n  \
    \ description oob_management\n   no shutdown\n   vrf MGMT\n   ip address 10.73.254.14/24\n\
    !\ninterface Vlan4094\n   description MLAG_PEER\n   no shutdown\n   mtu 1500\n\
    \   no autostate\n   ip address 172.31.253.5/31\n!\nip routing\nno ip routing\
    \ vrf MGMT\n!\nmlag configuration\n   domain-id DC1_LEAF2\n   local-interface\
    \ Vlan4094\n   peer-address 172.31.253.4\n   peer-link Port-Channel7\n   reload-delay\
    \ mlag 300\n   reload-delay non-mlag 330\n!\nip route vrf MGMT 0.0.0.0/0 10.73.254.253\n\
    !\nmanagement api http-commands\n   protocol https\n   no shutdown\n   !\n   vrf\
    \ MGMT\n      no shutdown\n!\nmanagement ssh\n   idle-timeout 0\n   no shutdown\n\
    \   vrf MGT\n      no shutdown\n!\nend\n"
  AVD_DC1-SPINE1: "!RANCID-CONTENT-TYPE: arista\n!\ndaemon TerminAttr\n   exec /usr/bin/TerminAttr\
    \ -cvaddr=10.73.254.1:9910 -cvvrf=MGMT -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata\
    \ -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -taillogs\n   no shutdown\n\
    !\nvlan internal order ascending range 1006 1199\n!\ntransceiver qsfp default-mode\
    \ 4x10G\n!\nservice routing protocols model multi-agent\n!\nhostname DC1-SPINE1\n\
    ip name-server vrf MGMT 10.73.1.254\nip name-server vrf MGMT 10.73.254.253\n!\n\
    snmp-server community inetsix-ro view test rw inetsix-snmp-acl\n!\nspanning-tree\
    \ mode mstp\nspanning-tree mst 0 priority 4096\n!\naaa authorization exec default\
    \ local\n!\nno aaa root\nno enable password\n!\nusername admin privilege 15 role\
    \ network-admin nopassword\nusername ansible privilege 15 role network-admin secret\
    \ sha512 $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/\n\
    username cvpadmin privilege 15 role network-admin secret sha512 $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.\n\
    username demo privilege 15 role network-admin secret sha512 $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/\n\
    !\nclock timezone Europe/Paris\n!\nvrf instance MGMT\n!\ninterface Port-Channel1\n\
    \   description DC1_LEAF1_Po1\n   no shutdown\n   switchport\n   switchport mode\
    \ trunk\n!\ninterface Port-Channel3\n   description DC1_LEAF2_Po1\n   no shutdown\n\
    \   switchport\n   switchport mode trunk\n!\ninterface Ethernet1\n   description\
    \ DC1-LEAF1A_Ethernet1\n   no shutdown\n   channel-group 1 mode active\n!\ninterface\
    \ Ethernet2\n   description DC1-LEAF1B_Ethernet1\n   no shutdown\n   channel-group\
    \ 1 mode active\n!\ninterface Ethernet3\n   description DC1-LEAF2A_Ethernet1\n\
    \   no shutdown\n   channel-group 3 mode active\n!\ninterface Ethernet4\n   description\
    \ DC1-LEAF2B_Ethernet1\n   no shutdown\n   channel-group 3 mode active\n!\ninterface\
    \ Management1\n   description oob_management\n   no shutdown\n   vrf MGMT\n  \
    \ ip address 10.73.254.1/24\n!\nip routing\nno ip routing vrf MGMT\n!\nip route\
    \ vrf MGMT 0.0.0.0/0 10.73.254.253\n!\nmanagement api http-commands\n   protocol\
    \ https\n   no shutdown\n   !\n   vrf MGMT\n      no shutdown\n!\nmanagement ssh\n\
    \   idle-timeout 0\n   no shutdown\n   vrf MGT\n      no shutdown\n!\nend\n"
  AVD_DC1-SPINE2: "!RANCID-CONTENT-TYPE: arista\n!\ndaemon TerminAttr\n   exec /usr/bin/TerminAttr\
    \ -cvaddr=10.73.254.1:9910 -cvvrf=MGMT -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata\
    \ -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -taillogs\n   no shutdown\n\
    !\nvlan internal order ascending range 1006 1199\n!\ntransceiver qsfp default-mode\
    \ 4x10G\n!\nservice routing protocols model multi-agent\n!\nhostname DC1-SPINE2\n\
    ip name-server vrf MGMT 10.73.1.254\nip name-server vrf MGMT 10.73.254.253\n!\n\
    snmp-server community inetsix-ro view test rw inetsix-snmp-acl\n!\nspanning-tree\
    \ mode mstp\nspanning-tree mst 0 priority 4096\n!\naaa authorization exec default\
    \ local\n!\nno aaa root\nno enable password\n!\nusername admin privilege 15 role\
    \ network-admin nopassword\nusername ansible privilege 15 role network-admin secret\
    \ sha512 $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/\n\
    username cvpadmin privilege 15 role network-admin secret sha512 $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.\n\
    username demo privilege 15 role network-admin secret sha512 $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/\n\
    !\nclock timezone Europe/Paris\n!\nvrf instance MGMT\n!\ninterface Port-Channel1\n\
    \   description DC1_LEAF1_Po1\n   no shutdown\n   switchport\n   switchport mode\
    \ trunk\n!\ninterface Port-Channel3\n   description DC1_LEAF2_Po1\n   no shutdown\n\
    \   switchport\n   switchport mode trunk\n!\ninterface Ethernet1\n   description\
    \ DC1-LEAF1A_Ethernet2\n   no shutdown\n   channel-group 1 mode active\n!\ninterface\
    \ Ethernet2\n   description DC1-LEAF1B_Ethernet2\n   no shutdown\n   channel-group\
    \ 1 mode active\n!\ninterface Ethernet3\n   description DC1-LEAF2A_Ethernet2\n\
    \   no shutdown\n   channel-group 3 mode active\n!\ninterface Ethernet4\n   description\
    \ DC1-LEAF2B_Ethernet2\n   no shutdown\n   channel-group 3 mode active\n!\ninterface\
    \ Management1\n   description oob_management\n   no shutdown\n   vrf MGMT\n  \
    \ ip address 10.73.254.2/24\n!\nip routing\nno ip routing vrf MGMT\n!\nip route\
    \ vrf MGMT 0.0.0.0/0 10.73.254.253\n!\nmanagement api http-commands\n   protocol\
    \ https\n   no shutdown\n   !\n   vrf MGMT\n      no shutdown\n!\nmanagement ssh\n\
    \   idle-timeout 0\n   no shutdown\n   vrf MGT\n      no shutdown\n!\nend\n"
CVP_TOPOLOGY:
  DC1_FABRIC:
    parent_container: Tenant
  DC1_L2LEAFS:
    parent_container: DC1_FABRIC
  DC1_LEAF1:
    devices:
    - DC1-LEAF1A
    - DC1-LEAF1B
    parent_container: DC1_L2LEAFS
  DC1_LEAF2:
    devices:
    - DC1-LEAF2A
    - DC1-LEAF2B
    parent_container: DC1_L2LEAFS
  DC1_SPINES:
    devices:
    - DC1-SPINE1
    - DC1-SPINE2
    parent_container: DC1_FABRIC
changed: false
