name: Test Installation
on:
  push:
  pull_request:
jobs:
  'setup':
    name: 'One liner installation'
    runs-on: self-hosted
    container: avdteam/base:3.6
    steps:
      - uses: actions/checkout@master
      - name: Execute one-liner installation
        run: |
          cd /tmp/
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/aristanetworks/ansible-avd/devel/development/install.sh)"
      - name: Run Makefile commands
        run: |
          cd /tmp/arista-ansible/
          cat Makefile
          make
